version: '3.9'

services:

  broker-1:
    image: streamnative/sn-pulsar:2.10.4.3
    platform: linux/amd64
    container_name: broker-1
    hostname: broker-1
    command: >
      bash -c "bin/apply-config-from-env.py conf/broker.conf &&
      exec bin/pulsar broker"
    environment:
      PULSAR_PREFIX_advertisedAddress: "localhost"
      PULSAR_PREFIX_allowAutoTopicCreation: "true"
      PULSAR_PREFIX_allowAutoTopicCreationType: partitioned
      PULSAR_PREFIX_brokerDeleteInactiveTopicsEnabled: "false"
      PULSAR_PREFIX_zookeeperServers: zookeeper:2181
      PULSAR_PREFIX_configurationStoreServers: zookeeper:2181
      PULSAR_PREFIX_clusterName: pulsar-cluster
      PULSAR_PREFIX_managedLedgerDefaultEnsembleSize: 1
      PULSAR_PREFIX_managedLedgerDefaultWriteQuorum: 1
      PULSAR_PREFIX_managedLedgerDefaultAckQuorum: 1
    ports:
      - 6650:6650 # Pulsar Binary
      - 8080:8080
    healthcheck:
      interval: 5s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8080/admin/v2/clusters/pulsar-cluster

networks:
  default:
    name: table-view-network
    external: true